version: '3.7'
services:
  gitea:
    image: pistacks/gitea:1.10.0
    networks:
      - pistack
      - db
    volumes:
      - gitea.vol:/data
    environment:
      - APP_NAME=Gitea
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=http://gitea.${DOMAIN}
      - SSH_DOMAIN=gitea.${DOMAIN}
      - SSH_PORT=2222
      - HTTP_PORT=3000
      - DB_TYPE=mysql
      - DB_HOST=gitea-db:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    deploy:
      labels:
        - traefik.port=3000
        - traefik.backend=gitea
        - traefik.frontend.rule=Host:gitea.${DOMAIN}

  gitea-db:
    image: pistacks/mysql
    networks:
      - db
    environment:
      - MYSQL_ROOT_PWD=password
      - MYSQL_USER=gitea
      - MYSQL_USER_PWD=gitea
      - MYSQL_USER_DB=gitea
    volumes:
      - gitea_db.vol:/var/lib/mysql

  drone-server:
    image: pistacks/drone-server:1.2.3
    networks:
      - pistack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - drone.vol:/var/lib/drone
    environment:
      - DRONE_DEBUG=true
      - DRONE_ADMIN=rbekker87
      - DRONE_USER_CREATE=username:pistacks,admin:true
      - DRONE_SERVER_PORT=:80
      - DRONE_DATABASE_DRIVER=sqlite3
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GITEA_SERVER=http://gitea:3000
      - DRONE_RPC_SECRET=xxxx
      - DRONE_SERVER_HOST=drone-server:80
      - DRONE_HOST=http://drone-server:80
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_AGENTS_ENABLED=true
      - DRONE_DATABASE_DATASOURCE=/database.sqlite
    deploy:
      labels:
        - traefik.port=80
        - traefik.backend=drone-server
        - traefik.frontend.rule=Host:drone.${DOMAIN}
      placement:
        constraints:
           - node.role==manager

  drone-agent:
    image: pistacks/drone-agent:1.2.3
    networks:
      - pistack
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_SERVER=http://drone-server:80
      - DRONE_RPC_SECRET=xxxx
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_AGENT="${HOSTNAME}"
      - DOCKER_OS=linux
      - DOCKER_ARCH=arm
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
           - node.role==worker

networks:
  pistack:
    external: true
  db:
    external: true

volumes:
  drone.vol: {}
  gitea.vol: {}
  gitea_db.vol: {}
